In [1]:
import jraph
import jax
import jax.numpy as jnp
import e3nn_jax as e3nn
import numpy as np


import sys
sys.path.append('..')


In [2]:
%load_ext autoreload

In [3]:
%autoreload 2
import train
import models
import datatypes
import analyses.generate_plots as generate_plots
import input_pipeline_tf
import configs.mace as mace
import analyses.analysis as analysis

In [14]:
# Mimic what we do in train.py.
config = mace.get_config()
config.max_n_graphs = 32
rng = jax.random.PRNGKey(0)
rng, dataset_rng = jax.random.split(rng)

# Obtain graphs.
datasets = input_pipeline_tf.get_datasets(dataset_rng, config)
train_iter = datasets["train"].as_numpy_iterator()
init_graphs = next(train_iter)

# Set up dummy variables to obtain the structure.
rng, init_rng = jax.random.split(rng)
net = train.create_model(config, run_in_evaluation_mode=False)
params = jax.jit(net.init)(init_rng, init_graphs)

/Users/ameyad/Documents/spherical-harmonic-net/notebooks/../input_pipeline_tf.py:86: FutureWarning: jax.tree_leaves is deprecated, and will be removed in a future release. Use jax.tree_util.tree_leaves instead.
  return np.shape(jax.tree_leaves(graph.nodes)[0])[0], np.sum(graph.n_edge), np.shape(graph.n_node)[0]


320 3008 32


In [16]:
print("padding")
print("nodes", config.max_n_nodes)
print("edges", config.max_n_edges)
print("graphs", config.max_n_graphs)

padding
nodes 512
edges 1024
graphs 32


In [20]:
count = 0
for step, graphs in enumerate(datasets["train"].as_numpy_iterator()):
    if step % 1000 == 1:
        print(step, count / step)
    if step == 10000:
        break

    graphs = jax.tree_map(jnp.array, graphs)
    graphs = datatypes.Fragments.from_graphstuple(graphs)
    count += jraph.get_graph_padding_mask(graphs).sum()

print(count / step)


1 21.0
1001 28.937063
2001 29.311344
3001 29.346884
4001 29.31467
5001 29.324135
6001 29.306782
7001 29.376661
8001 29.411823
9001 29.394289
29.3881


In [21]:
graphs = jraph.GraphsTuple(
    nodes=jnp.array([[1, 2, 3], [1, 2, 3], [4, 5, 6], [7, 8, 9]]),
    edges=jnp.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
    globals=jnp.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
    n_node=jnp.array([2, 1, 1]),
    n_edge=jnp.array([1, 1, 1]),
    senders=jnp.array([0, 0, 0]),
    receivers=jnp.array([0, 0, 0]),
)

In [40]:
num_graphs = 4
rng, *species_rngs = jax.random.split(jax.random.PRNGKey(0), num_graphs + 1)

target_species_probs = jnp.ones((num_graphs, models.NUM_ELEMENTS)) / models.NUM_ELEMENTS
target_species = jax.vmap(lambda key, p: jax.random.choice(
    key, models.NUM_ELEMENTS, p=p))((species_rngs,), target_species_probs)


ValueError: vmap got inconsistent sizes for array axes to be mapped:
  * most axes (4 of them) had size 2, e.g. axis 0 of argument key[0][0] of type uint32[2];
  * one axis had size 4: axis 0 of argument p of type float32[4,5]

In [43]:
e3nn.IrrepsArray("10x0e", jnp.arange(10))

10x0e [0 1 2 3 4 5 6 7 8 9]

In [49]:

myhost

'Ameyas-MacBook-Pro.local'

In [16]:
# Get results.
results = analysis.get_results_as_dataframe(generate_plots.ALL_MODELS, generate_plots.ALL_METRICS, "../potato_workdirs/v4/")

/Users/ameyad/Documents/spherical-harmonic-net/notebooks/../analyses/analysis.py:86: FutureWarning: jax.tree_leaves is deprecated, and will be removed in a future release. Use jax.tree_util.tree_leaves instead.
  num_params = sum(jax.tree_leaves(jax.tree_map(jnp.size, best_state.params)))


In [20]:
results['val'][results['val']['model'] == 'e3schnet'].sort_values('total_loss')

model  num_interactions  max_l  num_channels  num_params  total_loss  \
92   e3schnet                 7      5            32     1683936    1.251747   
80   e3schnet                10      5            32     2397792    1.251962   
77   e3schnet                10      4            32     1455488    1.269752   
84   e3schnet                 9      3            32      727264    1.272971   
110  e3schnet                 8      5            32     1921888    1.302418   
104  e3schnet                 6      5            32     1445984    1.355929   
68   e3schnet                 5      5            32     1208032    1.364659   
102  e3schnet                 6      3            32      490144    1.439990   
108  e3schnet                 8      3            32      648224    1.519992   
109  e3schnet                 8      2            32      321152    1.542620   
107  e3schnet                 8      4            32     1167808    1.546134   
85   e3schnet                 9      2            32      359456    1.549325   
83   e3schnet                 9      4            32     1311648    1.576939   
54   e3schnet                 3      3            32      253024    1.582864   
91   e3schnet                 7      2            32      282848    1.590444   
90   e3schnet                 7      3            32      569184    1.593694   
79   e3schnet                10      2            32      397760    1.598231   
65   e3schnet                 5      4            32      736288    1.619154   
78   e3schnet                10      3            32      806304    1.621916   
60   e3schnet                 4      3            32      332064    1.628937   
53   e3schnet                 3      4            32      448608    1.644624   
101  e3schnet                 6      4            32      880128    1.647379   
66   e3schnet                 5      3            32      411104    1.648390   
103  e3schnet                 6      2            32      244544    1.656316   
86   e3schnet                 9      5            32     2159840    1.661336   
61   e3schnet                 4      2            32      167936    1.687343   
67   e3schnet                 5      2            32      206240    1.705008   
89   e3schnet                 7      4            32     1023968    1.733417   
59   e3schnet                 4      4            32      592448    1.747436   
74   e3schnet                 2      5            32      494176    1.749235   
72   e3schnet                 2      3            32      173984    1.813919   
55   e3schnet                 3      2            32      129632    1.846169   
71   e3schnet                 2      4            32      304768    1.858110   
56   e3schnet                 3      5            32      732128    2.031657   
73   e3schnet                 2      2            32       91328    2.123212   
62   e3schnet                 4      5            32      970080    2.424970   
98   e3schnet                 1      5            32      256224    2.566564   
95   e3schnet                 1      4            32      160928    2.594467   
96   e3schnet                 1      3            32       94944    2.860718   
97   e3schnet                 1      2            32       53024    3.043672   
112  e3schnet                 8      1            32      136416    3.550571   
82   e3schnet                10      1            32      167136    3.612272   
88   e3schnet                 9      1            32      151776    3.612682   
94   e3schnet                 7      1            32      121056    3.626793   
106  e3schnet                 6      1            32      105696    3.638140   
70   e3schnet                 5      1            32       90336    3.710119   
64   e3schnet                 4      1            32       74976    3.747685   
58   e3schnet                 3      1            32       59616    3.897160   
76   e3schnet                 2      1            32       44256    4.139313   
100  e3s

In [47]:
import re
seed, start, end = [int(val) for val in re.findall(r'\d+', "fragments_seed01_from130944_to133920")]
start, end

(130944, 133920)

In [22]:
def segment_sample(probabilities, segment_ids, num_segments, rng):
    """Sample from a categorical distribution across each segment.
    Args:
        segment_ids: A 1D array of segment ids.
        probs: A 1D array of probabilities.
    Returns:
        A 1D array of samples.
    """
    def sample_for_segment(rng, i):
        return jax.random.choice(rng, node_indices, p=jnp.where(i == segment_ids, probabilities, 0.))
    
    node_indices = jnp.arange(len(segment_ids))
    rngs = jax.random.split(rng, num_segments)
    return jax.vmap(sample_for_segment)(rngs, jnp.arange(num_segments))

In [23]:
focus_logits = graphs.nodes.sum(axis=1)
probs = jraph.partition_softmax(focus_logits, graphs.n_node)
print(probs)
for seed in range(100):
    print(segment_sample(probs, jnp.asarray([0, 0, 1, 2]), 3, jax.random.PRNGKey(seed)))

[0.5 0.5 1.  1. ]
[0 2 3]
[1 2 3]
[0 2 3]
[0 2 3]
[0 2 3]
[1 2 3]
[0 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
[0 2 3]
[0 2 3]
[1 2 3]
[1 2 3]
[0 2 3]
[1 2 3]
[0 2 3]
[0 2 3]
[1 2 3]
[0 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
[0 2 3]
[0 2 3]
[0 2 3]
[0 2 3]
[1 2 3]
[0 2 3]
[1 2 3]
[1 2 3]
[0 2 3]
[0 2 3]
[1 2 3]
[1 2 3]
[0 2 3]
[0 2 3]
[0 2 3]
[1 2 3]
[0 2 3]
[1 2 3]
[1 2 3]
[0 2 3]
[0 2 3]
[1 2 3]
[1 2 3]
[0 2 3]
[1 2 3]
[1 2 3]
[0 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
[0 2 3]
[0 2 3]
[0 2 3]
[0 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
[0 2 3]
[1 2 3]
[0 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
[0 2 3]
[0 2 3]
[0 2 3]
[0 2 3]
[1 2 3]
[0 2 3]
[0 2 3]
[1 2 3]
[0 2 3]
[0 2 3]
[1 2 3]
[1 2 3]
[0 2 3]
[1 2 3]
[0 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
[0 2 3]
[0 2 3]
[1 2 3]
[1 2 3]
[0 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
[0 2 3]
[1 2 3]
[0 2 3]


In [3]:
nodes = jnp.asarray([2, 3, 1, 4])
segment_max = e3nn.scatter_max(nodes, nel=graphs.n_node)
segment_max_expanded = e3nn.scatter_max(nodes, map_back=True, nel=graphs.n_node)
print(segment_max_expanded)
# segment_max_expanded = jnp.asarray([segment_max[0], segment_max[0], segment_max[1], segment_max[2]])

expected = 0 + jnp.log(1 + e3nn.scatter_sum(jnp.exp(nodes - 0), nel=graphs.n_node))
computed = segment_max + jnp.log(jnp.exp(-segment_max) + e3nn.scatter_sum(jnp.exp(nodes - segment_max_expanded), nel=graphs.n_node))

expected, computed

[3. 3. 1. 4.]


(Array([3.3490124, 1.3132616, 4.01815  ], dtype=float32),
 Array([3.3490121, 1.3132616, 4.01815  ], dtype=float32))

In [54]:
import analysis


In [62]:
analysis.load_from_workdir("/Users/ameyad/Documents/spherical-harmonic-net/potato_workdirs/workdirs/mace/interactions=1/l=0/channels=32")

NameError: name 'mace_jax' is not defined

In [4]:
lmax = 3
irreps = e3nn.Irreps(e3nn.Irrep.iterator(lmax))
e3nn.IrrepsArray(irreps=irreps, array=jnp.ones((10, irreps.dim)))

1x0e+1x0o+1x1o+1x1e+1x2e+1x2o+1x3o+1x3e
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1

In [5]:
e3nn.scatter_sum(data=graphs.nodes, nel=graphs.n_node)

Array([[2., 4., 6.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32, weak_type=True)