In [1]:
import ase
import jax
import jax.numpy as jnp
import sys
sys.path.append('..')
import fragments
import input_pipeline

/Users/songk/miniconda3/envs/sh-net/lib/python3.10/site-packages/flax/struct.py:136: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(data_clz, keypaths)
/Users/songk/miniconda3/envs/sh-net/lib/python3.10/site-packages/flax/struct.py:136: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(data_clz, keypaths)


In [2]:
mol = ase.io.read("../analyses/molecules/downloaded/C6H6.xyz")
mol = input_pipeline.ase_atoms_to_jraph_graph(mol, jnp.asarray([1, 6, 7, 8, 9]), 1.5)

In [3]:
print(mol.senders)
print(mol.receivers)
print(mol.nodes.species)

[ 1  5  6  0  2  7  1  3  8  2  4  9  3  5 10  0  4 11  0  1  2  3  4  5]
[ 0  0  0  1  1  1  2  2  2  3  3  3  4  4  4  5  5  5  6  7  8  9 10 11]
[1 1 1 1 1 1 0 0 0 0 0 0]


In [7]:
for fragment in fragments.generate_fragments(
    jax.random.PRNGKey(1), mol, 2, heavy_first=True#, mode="radius"
):
    print(fragment.nodes.species)

[1]
[1 1]
[1 1 1]
[1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1 1]
[1 0 1 1 1 1 1]
[1 1 0 0 1 1 1 1]
[1 1 1 1 1 0 0 0 1]
[1 1 1 0 0 0 0 1 1 1]
[1 1 1 1 0 0 0 0 0 1 1]
[1 1 1 1 1 1 0 0 0 0 0 0]
