In [1]:
import jraph
import jax
import jax.numpy as jnp
import e3nn_jax as e3nn

/Users/songk/miniconda3/envs/sh-net/lib/python3.10/site-packages/flax/struct.py:136: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(data_clz, keypaths)
/Users/songk/miniconda3/envs/sh-net/lib/python3.10/site-packages/flax/struct.py:136: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(data_clz, keypaths)


In [19]:
# Undirected graph: CH4
ch3 = jraph.GraphsTuple(
    nodes=jnp.array([4, 1, 1, 1, 1]),  # electrons to be shared
    edges=jnp.array([0, 0, 0, 0]),  # bonds (initially empty)
    globals=None,
    senders=jnp.array([0, 0, 0, 0]),
    receivers=jnp.array([1, 2, 3, 4]),
    n_node=jnp.array([5]),
    n_edge=jnp.array([4]),
)

In [3]:
def allocate(graph, per_edge):
    """
    For each edge `e`, allocate `per_edge[e]` electrons from each vertex of the edge to the edge itself.
    """
    valence_edges = graph.edges
    valence_nodes = graph.nodes
    valence_senders = graph.senders
    valence_receivers = graph.receivers

    # update valence values per edge/node
    valence_edges = valence_edges + per_edge
    valence_nodes = valence_nodes.at[valence_senders].add(-per_edge)
    valence_nodes = valence_nodes.at[valence_receivers].add(-per_edge)

    return graph._replace(edges=valence_edges, nodes=valence_nodes)

In [4]:
def allocation_imposed(graph):
    """Computes the number of electrons to distribute per edge on the next allocation."""
    num_nodes = graph.nodes.shape[0]
    valence_edges = graph.edges
    valence_nodes = graph.nodes
    valence_senders = graph.senders
    valence_receivers = graph.receivers

    # Situation 1: Share electrons between nodes that have electrons to give
    node_alloc = jnp.zeros(num_nodes, dtype=jnp.int32)
    # for each edge, add 1 to each sender if receiver still has electrons to give
    node_alloc = node_alloc.at[valence_senders].add(valence_nodes[valence_receivers] > 0)
    # for each edge, add 1 to each receiver if sender still has electrons to give
    node_alloc = node_alloc.at[valence_receivers].add(valence_nodes[valence_senders] > 0)
    node_alloc = (node_alloc == 1) & (valence_nodes > 0)

    # for each edge, if sender or receiver has at least 1 electron to give,
    # set edge allocation to the smaller of the two valences
    edge_alloc1 = jnp.where(
        node_alloc[valence_senders] | node_alloc[valence_receivers],
        jnp.minimum(valence_nodes[valence_senders], valence_nodes[valence_receivers]),
        0
    )

    # Situation 2: If edge has no electrons, allocate 1 electron to that edge
    edge_alloc2 = jnp.maximum(0, 1 - valence_edges)

    edge_alloc = jnp.maximum(edge_alloc1, edge_alloc2)

    # Situation 3: If edge_alloc has no electrons being distributed, but some node has electrons to give,
    # choose a conformation in which to distribute electrons.


    return edge_alloc


def allocate_while_you_have_to(graph):
    def cond(graph):
        a = allocation_imposed(graph)
        return jnp.any(a > 0)

    def body(graph):
        a = allocation_imposed(graph)
        return allocate(graph, a)

    # return jax.lax.while_loop(cond, body, graph)
    while cond(graph):
        graph = body(graph)
        print(graph)
    return graph

In [5]:
def valence(graph):
    """
    0 = valence OK
    1 = Algorithm not finished
    2 = Impossible to satisfy valence
    """
    graph = allocate_while_you_have_to(graph)

    edge_mistakes = graph.edges < 1
    node_mistakes = graph.nodes < 0
    node_incomplete = graph.nodes > 0

    m = e3nn.scatter_sum(node_mistakes, nel=graph.n_node)
    m += e3nn.scatter_sum(edge_mistakes, nel=graph.n_edge)
    i = e3nn.scatter_sum(node_incomplete, nel=graph.n_node)

    return jnp.where(m == 0, jnp.where(i == 0, 0, 1), 2)

In [65]:
# CH4 (edges directed the opposite way)

graph = jraph.GraphsTuple(
    nodes=jnp.array([4, 1, 1, 1, 1]),  # electrons to be shared
    edges=jnp.array([0, 0, 0, 0]),  # bonds (initially empty)
    globals=None,
    senders=jnp.array([1, 0, 3, 4]),
    receivers=jnp.array([0, 2, 0, 0]),
    n_node=jnp.array([5]),
    n_edge=jnp.array([4]),
)
print(graph.nodes)
graph = allocate_while_you_have_to(graph)
print(graph.nodes)
valence(graph)

[4 1 1 1 1]
[0 0 0 0 0]


Array([0], dtype=int32, weak_type=True)

In [64]:
# Undirected graph: H-C-C-C-C-C-C-H
graph = jraph.GraphsTuple(
    nodes=jnp.array([1, 4, 4, 4, 4, 4, 4, 1]),  # electrons to be shared
    edges=jnp.array([0, 0, 0, 0, 0, 0, 0]),  # bonds (no electrons at initial state)
    globals=None,
    senders=jnp.array([0, 1, 2, 3, 4, 5, 6]),
    receivers=jnp.array([1, 2, 3, 4, 5, 6, 7]),
    n_node=jnp.array([9]),
    n_edge=jnp.array([7]),
)
print(graph.nodes)
graph = allocate_while_you_have_to(graph)
print(graph.nodes)

[1 4 4 4 4 4 4 1]
[0 0 0 0 0 0 0 0]


In [54]:
# Undirected graph: H-C-C-C-C-C-C-H
graph = jraph.GraphsTuple(
    nodes=jnp.array([1, 4, 4, 4, 4, 4, 4, 1]),  # electrons to be shared
    edges=jnp.array([0, 0, 0, 0, 0, 0, 0]),  # bonds (no electrons at initial state)
    globals=None,
    senders=jnp.array([0, 1, 2, 3, 4, 5, 6]),
    receivers=jnp.array([1, 2, 3, 4, 5, 6, 7]),
    n_node=jnp.array([9]),
    n_edge=jnp.array([7]),
)
valence(graph)

Array([0], dtype=int32, weak_type=True)

In [88]:
# Undirected graph: square
graph = jraph.GraphsTuple(
    nodes=jnp.array([3, 3, 3, 3]),  # electrons to be shared
    edges=jnp.array([0, 0, 0, 0]),  # bonds (no electrons at initial state)
    globals=None,
    senders=jnp.array([0, 1, 2, 3]),
    receivers=jnp.array([1, 2, 3, 0]),
    n_node=jnp.array([4]),
    n_edge=jnp.array([4]),
)
print(graph.nodes, graph.edges)
graph = allocate_while_you_have_to(graph)
print(graph.nodes, graph.edges)
valence(graph)

# nodes: [1 1 1 1]
# edges: [1 1 1 1]
# need to break the cycle somehow (i.e. just transfer electrons between (0, 1) and (2, 3), but not (1, 2) and (3, 0))

[3 3 3 3] [0 0 0 0]
[False False False False]
[False False False False]
[False False False False]
[1 1 1 1] [1 1 1 1]
[False False False False]


Array([1], dtype=int32, weak_type=True)

In [95]:
# manually force a change
nodes = jnp.array([0, 0, 1, 1])
edges = jnp.array([2, 1, 1, 1])
graph = graph._replace(nodes=nodes, edges=edges)
graph = allocate_while_you_have_to(graph)
print(graph.nodes, graph.edges)
valence(graph)

[False False  True  True]
[False False  True  True]
[False False False False]
[0 0 0 0] [2 1 2 1]
[False False False False]


Array([0], dtype=int32, weak_type=True)

In [77]:
# benzene
graph = jraph.GraphsTuple(
    nodes=jnp.array([4,4,4,4,4,4,1,1,1,1,1,1]),  # electrons to be shared
    edges=jnp.array([0,0,0,0,0,0,0,0,0,0,0,0]),  # bonds (no electrons at initial state)
    globals=None,
    senders=jnp.array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]),
    receivers=jnp.array([1, 2, 3, 4, 5, 0, 6, 7, 8, 9, 10, 11]),
    n_node=jnp.array([12]),
    n_edge=jnp.array([12]),
)
print(graph.nodes, graph.edges)
graph = allocate_while_you_have_to(graph)
print(graph.nodes, graph.edges)
valence(graph)

graph.nodes


[4 4 4 4 4 4 1 1 1 1 1 1] [0 0 0 0 0 0 0 0 0 0 0 0]
[False False False False False False  True  True  True  True  True  True]
[False False False False False False  True  True  True  True  True  True]
[False False False False False False False False False False False False]
[1 1 1 1 1 1 0 0 0 0 0 0] [1 1 1 1 1 1 1 1 1 1 1 1]
[False False False False False False False False False False False False]


Array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0], dtype=int32)

In [102]:
# furan - this DOES work
graph = jraph.GraphsTuple(
    nodes=jnp.array([4,4,4,4,2, 1,1,1,1]),  # electrons to be shared
    edges=jnp.array([0,0,0,0,0, 0,0,0,0]),  # bonds (no electrons at initial state)
    globals=None,
    senders=jnp.array([0, 1, 2, 3, 4, 0, 1, 2, 3]),
    receivers=jnp.array([1, 2, 3, 4, 0, 5, 6, 7, 8]),
    n_node=jnp.array([9]),
    n_edge=jnp.array([9]),
)
print(graph.nodes, graph.edges)
graph = allocate_while_you_have_to(graph)
print(graph.nodes, graph.edges)
valence(graph)

graph.nodes


[4 4 4 4 2 1 1 1 1] [0 0 0 0 0 0 0 0 0]
GraphsTuple(nodes=Array([1, 1, 1, 1, 0, 0, 0, 0, 0], dtype=int32), edges=Array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32), receivers=Array([1, 2, 3, 4, 0, 5, 6, 7, 8], dtype=int32), senders=Array([0, 1, 2, 3, 4, 0, 1, 2, 3], dtype=int32), globals=None, n_node=Array([9], dtype=int32), n_edge=Array([9], dtype=int32))
GraphsTuple(nodes=Array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32), edges=Array([2, 1, 2, 1, 1, 1, 1, 1, 1], dtype=int32), receivers=Array([1, 2, 3, 4, 0, 5, 6, 7, 8], dtype=int32), senders=Array([0, 1, 2, 3, 4, 0, 1, 2, 3], dtype=int32), globals=None, n_node=Array([9], dtype=int32), n_edge=Array([9], dtype=int32))
[0 0 0 0 0 0 0 0 0] [2 1 2 1 1 1 1 1 1]


Array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [100]:
# cyclopropane - this also works
graph = jraph.GraphsTuple(
    nodes=jnp.array([4,4,4, 1,1,1,1,1,1]),  # electrons to be shared
    edges=jnp.array([0,0,0, 0,0,0,0,0,0]),  # bonds (no electrons at initial state)
    globals=None,
    senders=jnp.array([0, 1, 2, 0, 0, 1, 1, 2, 2]),
    receivers=jnp.array([1, 2, 0, 3, 4, 5, 6, 7, 8,]),
    n_node=jnp.array([9]),
    n_edge=jnp.array([9]),
)
print(graph.nodes, graph.edges)
graph = allocate_while_you_have_to(graph)
print(graph.nodes, graph.edges)
valence(graph)

graph.nodes


[4 4 4 1 1 1 1 1 1] [0 0 0 0 0 0 0 0 0]
[False False False  True  True  True  True  True  True]
[False False False  True  True  True  True  True  True]
[False False False False False False False False False]
[0 0 0 0 0 0 0 0 0] [1 1 1 1 1 1 1 1 1]
[False False False False False False False False False]


Array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [6]:
# napthalene
graph = jraph.GraphsTuple(
    nodes=jnp.array([4,4,4,4,4,4,4,4,4,4, 1,1,1,1,1,1,1,1]),  # electrons to be shared
    edges=jnp.array([0,0,0,0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0]),  # bonds (no electrons at initial state)
    globals=None,
    senders=jnp.array([0, 1, 2, 3, 4, 5, 0, 6, 7, 8, 9, 1, 2, 3, 4, 6, 7, 8, 9]),
    receivers=jnp.array([1, 2, 3, 4, 5, 0, 6, 7, 8, 9, 5, 10, 11, 12, 13, 14, 15, 16, 17]),
    n_node=jnp.array([19]),
    n_edge=jnp.array([19]),
)
print(graph.nodes, graph.edges)
graph = allocate_while_you_have_to(graph)
print(graph.nodes, graph.edges)
valence(graph)

graph.nodes


[4 4 4 4 4 4 4 4 4 4 1 1 1 1 1 1 1 1] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
GraphsTuple(nodes=Array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32), edges=Array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32), receivers=Array([ 1,  2,  3,  4,  5,  0,  6,  7,  8,  9,  5, 10, 11, 12, 13, 14, 15,
       16, 17], dtype=int32), senders=Array([0, 1, 2, 3, 4, 5, 0, 6, 7, 8, 9, 1, 2, 3, 4, 6, 7, 8, 9], dtype=int32), globals=None, n_node=Array([19], dtype=int32), n_edge=Array([19], dtype=int32))
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0] [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


Array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [3]:
import ase.build

import sys
sys.path.append('..')
from analyses.check_valence import check_valence
import analyses.analysis as analysis

In [11]:
mol = ase.build.molecule("C6H6")
pybel = analysis.construct_pybel_mol(mol)

In [12]:
for atom in pybel.atoms:
    print(atom.OBAtom.GetExplicitDegree(), atom.OBAtom.GetExplicitValence())

3 4
3 4
3 4
3 4
3 4
3 4
1 1
1 1
1 1
1 1
1 1
1 1
